name: Snake GitHub Profile Animation

on:
  schedule:
    - cron: '0 */24 * * *'
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
     - name: generate-snake-grid-profile
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Kumala3
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
