name: Snake GitHub Profile Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Snake Game Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Kumala3
          outputs: dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: List output files
        run: ls -l ./dist/

      - name: Move generated SVG to the directory
        if: ${{ success() }}
        run: |
          mkdir -p ./dist
          mv ./dist/github-contribution-grid-snake-dark.svg ./dist/
          ls -l ./dist/
